version: "3.8"
services:
  app:
    image: maven:3.8.7-eclipse-temurin-17
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
    command: mvn spring-boot:run
    environment:
      - JAVA_OPTS=-Dspring.devtools.restart.poll-interval=1000 -Dspring.devtools.restart.quiet-period=500